networks:
    default:
        name: ac215-rag-network
        external: true
services:
    ac215-rag-cli:
        image: ac215-rag-cli
        container_name: ac215-rag-cli
        volumes:
            - ../secrets:/secrets
            - ../AC215_FormulaOnePenaltyTool:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GCP_PROJECT: $GCP_PROJECT
        depends_on:
            - chromadb
    chromadb:
        image: chromadb/chroma:latest
        container_name: ac215-rag-chromadb
        ports:
            - 8000:8000
        volumes:
            - ./docker-volumes/chromadb:/chroma/chroma
        environment:
            - IS_PERSISTENT=TRUE
            - ANONYMIZED_TELEMETRY=FALSE
            - CHROMA_CORS_ALLOW_ORIGINS=["*"] # This is not recommended for production environments.
